### ISSUE TITLE
Software code

### ISSUE THREAD

**Issue by ww9980** [linzi0928/-#1]
Hi 我是从B站来的，感谢分享，很喜欢！

在Readme中提到了user文件夹下软件代码，但是似乎并不包含在此处，请问可否上传谢谢！

PS，由于身处国外无法接收绑定了国内手机号的QQ登陆要的验证码所以没法加群，特此。

谢谢, 
9980

**Comment by linzi0928** [comment]
谢谢提醒，刚刚已经上传

**Comment by linzi0928** [comment]
> Hi 我是从B站来的，感谢分享，很喜欢！
> 
> 在Readme中提到了user文件夹下软件代码，但是似乎并不包含在此处，请问可否上传谢谢！
> 
> PS，由于身处国外无法接收绑定了国内手机号的QQ登陆要的验证码所以没法加群，特此。
> 
> 谢谢,
> 9980

谢谢提醒，刚已经上传，不知是否还需要？

**Comment by ww9980** [comment]
Great! 非常感谢。请问是否有QQ以外的联系方式？
